#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

if [ -z "$1" ]
  then
    device=/dev/sda
  else
    device=$1
fi

hdparm -I $device | grep "Serial Number" | xargs | awk '{ print $3 }' | md5sum | awk '{ print $1 }'
